### ISSUE TITLE
[feat] Octotree support bitbucket 

### ISSUE THREAD

**Issue by duyngle** [ovity/octotree#1001]
### Description
Make octotree support bitbucket

### Environment (if bug)

* Octotree version: 5.4.2
* Browser & version: edge  - 85.0.564.51
* OS & version: Mac 0.15.6
* Screenshot, if any (drag an image here)

<img width="2047" alt="Screen Shot 2020-09-13 at 6 49 59 PM" src="https://user-images.githubusercontent.com/4967217/93035570-27645900-f5f2-11ea-92b7-88b92cfed2c2.png">

* Console error log below this line

**Comment by KarenEfereyan** [comment]
@duyngle can I work on this?

**Comment by duyngle** [comment]
Yes please

**Comment by KarenEfereyan** [comment]
Thank you. Im currently looking at the codebase. I can ask for help, right?

**Comment by KarenEfereyan** [comment]
I just realized that I forked and cloned the support branch. No wonder, I did not see any code.

**Comment by buunguyen** [comment]
Hi, we don't intend to support BitBucket. We took that road in the past to support GitLab and BitBucket but while it's not too difficult to whip up the initial support, the effort to maintain was so much because GitHub, GitLab and BitBucket changed their UI and DOM regularly. Until we can afford significant more development bandwidth, I'm afraid this is not going to happen.

**Comment by KarenEfereyan** [comment]
> Hi, we don't intend to support BitBucket. We took that road in the past to support GitLab and BitBucket but while it's not too difficult to whip up the initial support, the effort to maintain was so much because GitHub, GitLab and BitBucket changed their UI and DOM regularly. Until we can afford significant more development bandwidth, I'm afraid this is not going to happen.

Okay
