### ISSUE TITLE
Icons not showing properly

### ISSUE THREAD

**Issue by withrvr** [ovity/octotree#1111]
### Description
![image](https://user-images.githubusercontent.com/69628500/147602642-cfe9b122-638e-4f10-afd2-56b65552cd9c.png)

y all icons logo  ... of files is not working properly 
I am using this [File Icons for GitHub and GitLab](https://github.com/homerchen19/github-file-icons)

### Environment (if bug)

* Octotree version:
* Browser & version:
* OS & version:
* Screenshot, if any (drag an image here)
* Console error log below this line

**Comment by danhgit** [comment]
Hi, that's the default mode. If you're still in trial or upgrade to Pro, you can change to other icon sets:

<img src="https://user-images.githubusercontent.com/38257704/147603381-d58b3cc3-3625-472e-b075-4b2f32136108.gif" width="500" >

Since this works as expected. Gonna close it. BTW, issue 1111. Nice :)
