### ISSUE TITLE
Feature request: Surface whether you've approved a PR in the PR list view

### ISSUE THREAD

**Issue by charmsRace** [ovity/octotree#1134]
### Feature request: Display user's PR approval status

The PR list view is extremely useful — I think for me, the biggest missing piece is being able to easily see whether I've already reviewed a given PR. This would let me quickly scan for PRs that still need my attention. I'll defer specific ideas for design to you guys.

There are some other things you might consider — say, displaying the general status you have in relationship to a PR, which I would enumerate as review not requested, review requested, reviewed with comments, reviewed with changes requested, and approved.

The PR list popover is one of my favorite (most-used) features. Long-term, you may consider making it a first-class view (i.e. with its own panel view, so you could present filters for draft status, review requested, etc.) — but that's just an idle suggestion.

**Comment by danhgit** [comment]
Hi, we've added a filter to the PR list in v7.7. We use the same review filter options that GitHub uses in the pull request page, so that we can utilize their API and maintain consistency. Hope this works out for you.

<img width="412" alt="image" src="https://user-images.githubusercontent.com/38257704/197098857-222bfc67-aeaf-4240-8ba5-4b903edcd4bd.png">
