### ISSUE TITLE
Support custom GitHub instances in Firefox & Safari

### ISSUE THREAD

**Issue by tofi86** [ovity/octotree#275]
It would be nice if you could also support custom GitLab instances ("enterprise") with the Firefox plugin.
Any chance?

**Comment by buunguyen** [comment]
Yeah, that's a limitation. It's not possible for GitHub too. Firefox basically requires domain permissions to be known [at build time](https://github.com/buunguyen/octotree/tree/master/src/config/firefox). 

One way to make it work is creating a custom build of Octotree with your enterprise domain names specified in the addon configs linked above.

If anyone knows of a way to work around this limitation, I'd love to hear about it or receive a PR.

**Comment by tofi86** [comment]
oh, okay, what a pitty... :-(
But we can leave this open until someone comes up with a solution...

**Comment by cmhe** [comment]
Wouldn't that be possible if this extension was a Greasemonkey user script? There you could at least specify applicable domains/urls yourself. Maybe take a look at the [Greasemonkey addon](https://github.com/greasemonkey/greasemonkey).

**Comment by evaryont** [comment]
I don't know if you've considered this already, but what about setting the addon to be included on *every* page? Hopefully, you can tell Firefox to inject only a tiny URL checking shim instead of the full addon. Then enabling/disabling self-hosted sites would be a configuration setting like in Chrome/Safari.

**Comment by alerque** [comment]
As much as I want to get this working on my private Gitlab instance, @evaryont I'm not sure I'd _want_ to trust an extension that knows my private API token with running on every site I visit. It seems like the attack surface goes up by several orders of magnitude if you do that. The Firefox limitation is there for a reason (I think).

**Comment by tabdulradi** [comment]
Is there any docs how to build Octotree's Firefox plugin?

**Comment by buunguyen** [comment]
@tabdulradi 

```
npm i
gulp dist
```

**Comment by Clijsters** [comment]
Would go with @evaryont's suggestion. E.g. Toggl is doing it the same way and I'm fine with that. What's with chrome? Couldn't find any configuration options for custom URLs

**Comment by buunguyen** [comment]
I'm hoping as Firefox moves to web extensions, it will support the same permission model as Chrome. When this PR is landed https://github.com/buunguyen/octotree/pull/403, I hope one of you can help verify.

**Comment by marsjaninzmarsa** [comment]
Due to landed #403 and [no known blockers](https://github.com/buunguyen/octotree/pull/403#issuecomment-317868953) for extending Chrome implementation to Firefox, we can move forward with that. Is mutual issue for both Safari and Firefox still preferred place for this, or we should split it as two mostly unrelated (in terms of implementation complexity) issues?

**Comment by buunguyen** [comment]
@marsjaninzmarsa I'd love a PR more than anything :)

**Comment by marsjaninzmarsa** [comment]
@buunguyen on my checklist, just when I'll have time.

**Comment by srodenberg** [comment]
I'm interested in this feature and it looks like nobody is actively working on it. Unfortunately I'm not a JS dev. I get an exception when building the project due to not having the proper key to sign the chrome release I believe, that being said the firefox portion of the build seems to work and I end up with a firefox.zip to launch. I tried a test run with a couple changes.

1. Added background.js/overrides.js to firefox config and changed chrome references to firefox.
2. Remove the ifdef for showing the enterprise github urls only in chrome.

That caused the plugin to fail to launch on a repo and I had trouble figuring out which error was related to the plugin. If anyone had a moment to point me in the right direction I would really appreciate it.

**Comment by buunguyen** [comment]
@srodenberg you can look at this PR to see how to get around the chrome build https://github.com/buunguyen/octotree/pull/461.

**Comment by timofonic** [comment]
I would like that, plus GitLab support. But I understand the limitations. Maybe further Firefox versions can make it possible?

**Comment by 5punk** [comment]
@buunguyen how do you add support for enterprise url?
I added the enterprise url to the manifest, created a bundle and added it as a temporary add-on. But the extension does not show up on enterprise urls.

**Comment by 5punk** [comment]
<img width="254" alt="image" src="https://user-images.githubusercontent.com/8335261/38637648-a224fc58-3d80-11e8-9fe0-e59ef25b452a.png">
it shows up as an invisible frame

**Comment by calebmeyer** [comment]
@5punk I followed the same steps (edit manifest, npm install, npm run dist), and dug in a little further. There's a JavaScript console error `Empty string passed to getElementById().`

It appears to be from this line (which is unfortunately minified): 
![image](https://user-images.githubusercontent.com/3342777/38829699-964f4c14-417f-11e8-9ed6-181e7f7cc847.png)

That makes the `.octotree_view_header` and `.octotree_view_body>ul` both empty (they're populated on a regular github repo):
![image](https://user-images.githubusercontent.com/3342777/38829819-e4e8b00e-417f-11e8-9a43-31d4056896f2.png)

**Comment by buunguyen** [comment]
We support GitHub Enterprise in Octotree Pro: https://www.octotree.io/. It will work on Chrome, Firefox and Opera. Octotree Pro requires a subscription and comes with some other advanced features (e.g. dark mode, file search etc.). Please consider subscribe to use these features as well as support the ongoing development of Octotree.
