### ISSUE TITLE
Not showing all files in pull request view

### ISSUE THREAD

**Issue by PapsOu** [ovity/octotree#504]
### Description
Go to this PR : https://github.com/sil-project/Platform/pull/50/files

You can see more than 161 files.

The octotree plugin, that init the tree at page load, does not have the full file tree loaded, because Github load async the file list. So, as seen in the attached screenshot, the folder src/Sil/Bundle/ProductBundle/Resources/ is not shown

### Environment

* Octotree version: 2.4.6
* Browser & version: Firefox 60 Developer Edition
* OS & version: Ubuntu 16.04 up to date
* Screenshots :
![20180327-170439](https://user-images.githubusercontent.com/5792207/37976118-03c22d88-31e1-11e8-8e9e-0aea739d4f47.png)

**Comment by stevennoto** [comment]
I looked into this one and I think I have a solution. The problem is that the PR API only returns the first 100 files. (The [documentation](https://developer.github.com/v3/pulls/#list-pull-requests-files) says that it returns 300 but for public repos, it is returning 100).

I have made a branch that changes the function which calls the API to do so recursively, until all diffs are fetched. @buunguyen, I will open a PR in this repo. Let me know what you think. Thanks!

**Comment by stychu** [comment]
Status? This is kinda annoying

**Comment by alexanderific** [comment]
Doesn't look like there's been activity on https://github.com/ovity/octotree/pull/569 since November. @stevennoto @buunguyen @duylam Is there still some deliberation outstanding about the approach for fetching the files beyond 100+? I see a couple different approaches discussed (iteratively calling the API if prompted to do so vs fetching the diff file and parsing that out), but didn't see any decision. Do you guys still need help?

At the least, it might be worth at the very least updating the note in the Settings to reflect 100 instead of 300. 

Willing to help if you're still on the prowl, but I'm not sure if there have been any movement on a different issue/PR that I haven't noticed. Thanks!

**Comment by stevennoto** [comment]
Hi @alexanderific, sorry for the delay.

I hope to return to this PR, but things are busy at my day job. 😅 Feel free to jump in if you like. The discussion in the PR thread seems to point to a good solution approach, but the PR will also have to be brought up to date with master, due to the merge conflict.

**Comment by buunguyen** [comment]
We're showing up to 3000 files now. But could be slow for very large PRs. We'll optimize perf.

**Comment by minhhunghuynh1106** [comment]
5
