### ISSUE TITLE
Safari latest update

### ISSUE THREAD

**Issue by vigo** [ovity/octotree#539]
### Description
After todays update on Safari, octotree is gone :(

### Environment (if bug)

* Octotree version:
* Browser & version: Version 12.0 (13606.2.11)
* OS & version: OSX 10.13.6 (17G65)
![screen shot 2018-09-18 at 17 11 41](https://user-images.githubusercontent.com/82952/45693511-f0275280-bb65-11e8-85a6-de078c832fec.png)

* Screenshot, if any (drag an image here)

Please help! :)

**Comment by vigo** [comment]
@ravicious well, maybe we "Safari" users should start a mini campaign? If we find 10 people, $99/10 less than $10 for each person? Who wants to help? ✋

**Comment by darrenchaker** [comment]
Thank you for the update! Very simple to add even for novice user - Best, Darren Chaker

**Comment by tbodt** [comment]
I have an apple developer program membership, and I'd be willing to volunteer that to put Octotree in the app store. @buunguyen

**Comment by sandangel** [comment]
any update on this? Really need this to use safari, chrome and firefox use too much memory on my machine

**Comment by buunguyen** [comment]
@tbodt thanks. I'll review safari support and let you know if I need help publishing.

**Comment by tomisacat** [comment]
Any update?

**Comment by thesunwave** [comment]
Is there any update?

**Comment by loveforgeter** [comment]
any update😞?

**Comment by rozag** [comment]
> @tbodt thanks. I'll review safari support and let you know if I need help publishing.

Is there any update on that?

**Comment by IvanMwiruki** [comment]
@buunguyen Any updates? Would really love to have safari support back.

**Comment by linjson** [comment]
@buunguyen when do you support on **safari 12**!!!!!!

**Comment by andreasowczarek** [comment]
You might find this one helpful https://georgegarside.com/blog/macos/install-any-safari-extension-macos-mojave/

**Comment by linjson** [comment]
@andreasowczarek, very good!!

**Comment by buunguyen** [comment]
I'm excited to announce that Octotree Pro is now an official Safari App Extension: https://itunes.apple.com/us/app/octotree-pro/id1457450145?mt=12.

This is a premium version of Octotree that has advanced features such as dark mode, file search etc. You can learn more about Octotree pro here: https://www.octotree.io/.

Why no free version for Safari? Because Apple requires paid membership to publish extensions. Worse, they require developers to go through the dreadful, time-consuming app reviewing process for every release because they recently treat extension as native app released to App Store. Octotree Pro is a complete redesign and simply a better software. By paying for Octotree Pro subscription, you'll help me continue develop and improving Octotree.

**Comment by tbodt** [comment]
Can I compile it myself for safari?

**Comment by buunguyen** [comment]
@tbodt 	I don't see why not. Currently only Octotree is open-source. Octotree Pro is built on Octotree, but the extra features are closed source for now. You can build Octotree and run on Safari if you want, can't promise it's a pleasant experience because Safari does make things difficult.
