### ISSUE TITLE
Display TOC for long readme file

### ISSUE THREAD

**Issue by zhanba** [ovity/octotree#570]
### Description
It's very useful to display Toc for a very long readme file, please consider it!!

### Environment (if bug)

* Octotree version:
* Browser & version:
* OS & version:
* Screenshot, if any (drag an image here)
* Console error log below this line

**Comment by nphi1212** [comment]
Might I ask what TOC stands for?

**Comment by buunguyen** [comment]
Table of content

**Comment by Mottie** [comment]
There are alternatives already available:

* https://github.com/arthurhammer/github-toc (browser extension).
* https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-table-of-contents (userscript; [install instructions](https://github.com/Mottie/GitHub-userscripts#installation)).

If you want to add a TOC to your own readme, there are other solutions:

* Use ASCIIdoc instead of markdown - it's built-in.
* Built in on wiki pages, add `__TOC__`.
* There are several VSCode extensions that will add a TOC for you.
* Online sites, e.g. http://doctoc.herokuapp.com/, http://tableofcontent.eu/ & https://imthenachoman.github.io/nGitHubTOC/.
* Command line: https://github.com/ekalinin/github-markdown-toc

There is a huge discussion about it here: https://github.com/isaacs/github/issues/215

**Comment by danhgit** [comment]
So I looked into this and noticed GitHub already supported showing the TOC. I'm not sure if it's a new feature or not but it seems convenient for me. I don't think it's worth it to re-build the functionality in Octotree.
