### ISSUE TITLE
Sidebar on the right overlapping contents

### ISSUE THREAD

**Issue by neo-cheung** [ovity/octotree#657]
### Description
When moving sidebar to the right some contents are overlapped by the sidebar and the scroll bar also overlapped the side bar

### Environment (if bug)

* Octotree version: Octotree Pro 1.0.2
* Browser & version: Chrome 73.0.3683.103 (Official Build) (64-bit)
* OS & version: Windows 10 Pro 17763.437

function properly on left
![image](https://user-images.githubusercontent.com/28858412/56104385-0cf3ff00-5f6a-11e9-97bf-c8eb757315dc.png)

overlapping on right
![image](https://user-images.githubusercontent.com/28858412/56104432-3c0a7080-5f6a-11e9-847e-e14f05c7ba56.png)

**Comment by buunguyen** [comment]
Yup, this is a known issue. I'm not sure how to best deal with it because while pushing content to the right (in the case of left dock) seems okay, pushing content to the left feels weird. Any idea?

**Comment by neo-cheung** [comment]
in most of the time it won't has overlapping problem (full screen) but when I align multiple windows (not enough width for all contents), pushing content to left will be batter than overlapping

![image](https://user-images.githubusercontent.com/28858412/56108766-11c3ad80-5f80-11e9-8948-c042946f42f0.png)

**Comment by CollinChaffin** [comment]
Suddenly the very same version that broke out the paid "pro" version, now the free version is totally unusable and worse, made the entire Github site unusable to the point that I now have to just disable it all together.  

EVERY single load now I get the Chrome credential popup over the Octotree pane (guessing something to do with a change to how the token field is tagged being flagged by Chrome as a "password" field for Github), so I first have to escape/close that, and then forget it anyway because ~75% of the time (again this worked ~95%+ the very last version) the pane no longer properly shifts content and the page is UNREADABLE as shown in other comments/screenshots above.

I just don't understand how or why the code could have (or needed to) enough to break the pane pinning that has literally worked for over a year and produce a totally erroneous login/cred popup that also never once appeared until now.  There is absolutely no way I would pay for pro if the free is now this broken so hopefully it gets addressed quickly but the comments above from days ago do not sound very confident that it will.

**Comment by neo-cheung** [comment]
@CollinChaffin I don't have the Chrome credential popup problem

if the panel using default (left) content also shifts correctly

the only problem so far is when i use "move the panel to right" (pro feature) it won't shift the content

**Comment by buunguyen** [comment]
> EVERY single load now I get the Chrome credential popup over the Octotree pane (guessing something to do with a change to how the token field is tagged being flagged by Chrome as a "password" field for Github), so I first have to escape/close that, and then forget it anyway because ~75% of the time (again this worked ~95%+ the very last version) the pane no longer properly shifts content and the page is UNREADABLE as shown in other comments/screenshots above.

We fix this in 3.0.4. It's caused by the change to make token textbox a password field, to make it more secure (i.e. avoid someone peaking over the shoulder). But it causes the password prompt to show. Trade off, trade off! Now just don't enter the token when someone with photographic memory standing behind one's back.

Please give the new version a try and let me know if there's still issue.

**Comment by buunguyen** [comment]
@neo-cheung we're considering options and will address this one way or another. Honestly, I'm not a fan of shifting content to the left (feel weird, but I'm a ltr reader :). But with pin mode, I suppose it's okay as sidebar is always there. Thanks again for reporting the issue.

**Comment by CollinChaffin** [comment]
I can confirm the password box has been addressed and no longer appears so good job there!  The overlap even in 3.04 still can be reproduced by moving forward then clicking "back" to re-visit the prior Github repo.  At least on my tests, it always still fails to re-shift the content to the right and the overlap occurs.  On new page loads, it does appear to be shifting initially a bit better.

**Comment by nphi** [comment]
@CollinChaffin ! Thanks for reporting issues. We will work on this. In the meantime, you could use the shortkeys option in Octotree settings to open and close the sidebar. It would work as expected.

Many thanks.

**Comment by nphi** [comment]
@buunguyen, this issue is fixed
