### ISSUE TITLE
Pjax break work on filepath

### ISSUE THREAD

**Issue by zWingz** [ovity/octotree#686]
### Description
at [home page](https://github.com/ovity/octotree), pjax work in change file
but if at [file page](https://github.com/ovity/octotree/blob/v3/src/core.plugins.js), pjax can't work

### Environment (if bug)

* Octotree version: @latest
* Browser & version: chrome@73
* OS & version: MacOS 10.14

**Comment by nphi** [comment]
@zWingz !
Just to clarify, this issue occurs even without Octotree. We just fixed the home page yesterday. And now we have been fixing this issue in the file page to help Octotree users have a better UX while navigating files.

Thanks for reporting the issue so that together we could make the Octotree better for everyone.

**Comment by zWingz** [comment]
thanks

**Comment by buunguyen** [comment]
Fix in 3.0.6.
