### ISSUE TITLE
Brave Browser shows access token in clear text

### ISSUE THREAD

**Issue by mengesb** [ovity/octotree#894]
### Description
Access tokens are shown in clear text on Brave Browser with extension installed

### Environment (if bug)

* Octotree version: 4.1.7
* Browser & version: Version 1.4.95 Chromium: 80.0.3987.122 (Official Build) (64-bit)
* OS & version: macOS Mojave 10.14.6
* Screenshot, if any (drag an image here) - N/A - really don't want to show my token =)
* Console error log below this line

**Comment by buunguyen** [comment]
This is intentional for now. Octotree supports multiple GitHub accounts, so showing the initial characters would help people to differentiate among these tokens. It is probably very rare if someone expands the sidebar big enough to reveal the entire token. That being said, Octotree 6 supports OAuth, that wouldn't reveal token in the UI at all. Please consider authenticating with OAuth instead.

**Comment by mengesb** [comment]
Does this mean Octotree supports OAuth for GHES as well? My impression is that it currently does not, thus this is still an issue ultimately

**Comment by buunguyen** [comment]
You're right. OAuth only works for github.com authentication at the moment. 

Does the token reveal completely in your typical usage? Or do you worry that you might incidentally reveal it?

**Comment by mengesb** [comment]
In my scenario (because of wife display) the whole token is visible. It's just bad practice. At least hide it using standard password masking with dots even if it's for system clear text.

The oauth path should be supported via GHES too, then you can get rid of that field all together, but at least mask the display.
