### ISSUE TITLE
Allow conditional pinning

### ISSUE THREAD

**Issue by kylemh** [ovity/octotree#937]
### Description
I am happy that we can lazyload the side bar, because I always want it open; however, for repositories with massive folder structures - such as DefinitelyTyped - there's a huge performance crush on the tree.

Basically I should be able to somehow say: "Don't pin if I'm looking at DefinitelyTyped" because I know it'll slow me down.

**Comment by buunguyen** [comment]
For very large repo, the best option is probably enable "lazy loading" for it. You can enable lazy loading for all repositories. With the Pro version, you can enable it for specific repositories. 

Allowing users to choose which repos to show Octotree is a good idea. If there's enough demand, we could build it.

**Comment by kylemh** [comment]
Lazy loading still attempts to load after my page loads. I don’t want it to load at all for some repos.

**Comment by buunguyen** [comment]
Now that per-repository lazy loading is a standard/free feature and because Octotree loads very fast with 6.0, I don't think this issue is as much relevant as it was. The UX/UI will be quite complicated to get this right but little value I think. Gonna close it now. If people feel strongly about it, we will re-consider.
